version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - cd docs
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  base-directory: 'docs/src/.vuepress/dist'
  files:
    - '**/*'
  #name: BuildArtifact
