version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - cd docs
      - npm install

  build:
    commands:
      - npm run build
      - mkdir dep
      - mkdir dep/version1
      - mv src/.vuepress/dist/* dep/version1/

artifacts:
  files:
    - '**/*'
  discard-paths: no
  #base-directory: 'docs/src/.vuepress/dist'
  base-directory: 'docs/dep'
